name: DTool CI

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: get-ppremake
      run: sudo wget -c https://github.com/toontownretro/ppremake/releases/download/v1.23/ppremake-v1.23-linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local/bin
    
    - name: ppremake
      run: ppremake
